# Tensor

In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see Bridge with NumPy). Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autograd section). 

In [1]:
import torch
import numpy as np

# Initializing a Tensor

### Directly from data

In [4]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

### From a NumPy array

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### From another tensor

In [14]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float64) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0549, 0.2586],
        [0.1766, 0.4467]], dtype=torch.float64) 



### With random or constant values:

In [20]:
shape = (2, 3, )
rand_tensor = torch.rand(shape, dtype = torch.float32)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3853, 0.9692, 0.2894],
        [0.1819, 0.8006, 0.6134]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

In [22]:
tensor = torch.rand((3,4,),  dtype = torch.float64)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float64
Device tensor is stored on: cpu


# Operations on Tensors

In [25]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [26]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [37]:
x = torch.randn(2, 3)
x_0 = torch.stack((x, x)) # dim = 0
print(x_0)
x_1 = torch.stack((x, x), dim = 1)
print(x_1)
x_2 = torch.stack((x, x), dim = 2)
print(x_2)
x_3 = torch.stack((x, x), dim = -3)
print(x_3)

tensor([[[ 0.7171, -0.8375, -1.4845],
         [ 0.7984,  0.9711, -0.8989]],

        [[ 0.7171, -0.8375, -1.4845],
         [ 0.7984,  0.9711, -0.8989]]])
tensor([[[ 0.7171, -0.8375, -1.4845],
         [ 0.7171, -0.8375, -1.4845]],

        [[ 0.7984,  0.9711, -0.8989],
         [ 0.7984,  0.9711, -0.8989]]])
tensor([[[ 0.7171,  0.7171],
         [-0.8375, -0.8375],
         [-1.4845, -1.4845]],

        [[ 0.7984,  0.7984],
         [ 0.9711,  0.9711],
         [-0.8989, -0.8989]]])
tensor([[[ 0.7171, -0.8375, -1.4845],
         [ 0.7984,  0.9711, -0.8989]],

        [[ 0.7171, -0.8375, -1.4845],
         [ 0.7984,  0.9711, -0.8989]]])


### Arithmetic operations

In [56]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [57]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


## Bridge with NumPy

### Tensor to NumPy array

In [62]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [63]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [64]:
n = np.ones(5)
t = torch.from_numpy(n)

In [65]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
